// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSDWhwCCtXAdtKZST6cdFdzdUuUJNGNZo',
    appId: '1:344722136955:web:47351167d146e8c538a7de',
    messagingSenderId: '344722136955',
    projectId: 'blog-app-63fc3',
    authDomain: 'blog-app-63fc3.firebaseapp.com',
    storageBucket: 'blog-app-63fc3.firebasestorage.app',
    measurementId: 'G-YXP4D3T6X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKdP00MRets2QrDVhGXkgryla6pMoQMRg',
    appId: '1:344722136955:android:b170859c2b97264e38a7de',
    messagingSenderId: '344722136955',
    projectId: 'blog-app-63fc3',
    storageBucket: 'blog-app-63fc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD0h2QnrJxL5WeE9ss3_n_lw0X6efqtqs',
    appId: '1:344722136955:ios:2e89602fd04d5ef538a7de',
    messagingSenderId: '344722136955',
    projectId: 'blog-app-63fc3',
    storageBucket: 'blog-app-63fc3.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD0h2QnrJxL5WeE9ss3_n_lw0X6efqtqs',
    appId: '1:344722136955:ios:2e89602fd04d5ef538a7de',
    messagingSenderId: '344722136955',
    projectId: 'blog-app-63fc3',
    storageBucket: 'blog-app-63fc3.firebasestorage.app',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSDWhwCCtXAdtKZST6cdFdzdUuUJNGNZo',
    appId: '1:344722136955:web:e4b2dbd9497b5dbc38a7de',
    messagingSenderId: '344722136955',
    projectId: 'blog-app-63fc3',
    authDomain: 'blog-app-63fc3.firebaseapp.com',
    storageBucket: 'blog-app-63fc3.firebasestorage.app',
    measurementId: 'G-FBJM5SYMLG',
  );
}
